# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-04 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='courses',
        ),
        migrations.DeleteModel(
            name='Cohort',
        ),
    ]
