FROM ubuntu:18.04
LABEL maintainer=Tito

# Install required packages and remove the apt packages cache when done.
RUN apt-get update \
  && apt-get upgrade -y \
  && apt-get install -y build-essential \
                        python3 \
                        python3-dev \
                        python3-setuptools \
                        python3-pip \
                        mysql-client \
                        libsasl2-dev \
                        libldap2-dev \
                        libpq-dev \
                        postgresql-client \
                        libmysqlclient-dev \
#                        supervisor \
#                        nginx \
                        vim \
 && pip3 install -U pip setuptools \
  # perform clean-up
 && rm -rf /var/lib/apt/lists/*

#create and change working directory
WORKDIR /home/vlabsServer

#copy requirements and install
COPY ./src/requirements.txt .
RUN pip3 install -r requirements.txt

#create django environment variable to be used in settings.py
ENV DJANGO_ENV=dev-docker

# copy rest of the code
COPY ./src .

EXPOSE 80
CMD ["python3", "manage.py", "runserver"]

