FROM ubuntu:18.04
LABEL maintainer=Tito

# Install required packages and remove the apt packages cache when done.
RUN apt-get update \
  && apt-get upgrade -y \
  && apt-get install -y build-essential \
                        python3 \
                        python3-dev \
                        python3-setuptools \
                        python3-pip \
                        mysql-client \
                        libsasl2-dev \
                        libldap2-dev \
                        libpq-dev \
                        postgresql-client \
                        libmysqlclient-dev \
                        supervisor \
                        nginx \
                        vim \
 && pip3 install -U pip setuptools \
  # perform clean-up
 && rm -rf /var/lib/apt/lists/*

# install uwsgi now because it takes a little while
RUN pip3 install uwsgi

#create and change working directory
WORKDIR /home/vlabsServer

#copy requirements and install
COPY ./src/requirements.txt .
RUN pip3 install -r requirements.txt

#create django environment variable to be used in settings.py
ENV DJANGO_ENV=dev

# copy rest of the code
COPY ./src .

#RUN mkdir -p static
# collect django static file
# run  makemigrations and migrate to prepare database
# since we are using sqlite for development ... dont do in production
# because database is not connected and it will not be ready
RUN python3 manage.py makemigrations \
  && python3 manage.py migrate \
  && python3 manage.py collectstatic --noinput


COPY dockerConfigs/nginx/vlabsServer_nginx.conf /etc/nginx/conf.d/default.conf

COPY dockerConfigs/supervisor/supervisor-app.conf /etc/supervisor/conf.d/

EXPOSE 80
CMD ["supervisord", "-n"]

