version: '3.1'

services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - DJANGO_ENV=production-docker
    restart: always
    command: bash -c "python3 manage.py makemigrations
                  && python3 manage.py migrate
                  && python3 manage.py collectstatic --noinput
                  && supervisord -n"
    ports:
      - "8080:80"
    depends_on:
      - db 

volumes:
  pg_data:
