database:
  ENGINE: django.db.backends.postgresql
  HOST: db
  PORT: 5432
  NAME: inwkauth
  USER: inwkadmin
  PASSWORD: W3tw0rk5!

security:
  SECRET_KEY: y60(c%^ya#5!#x5c7e$4m0cni08ythswo9df)e!^ngaq29acb+
  ALLOWED_HOSTS:
    - '*'
  DEBUG: false
  TIME_ZONE: America/Halifax

ldap:
  AUTH_LDAP_SERVER_URI: ldap://129.173.143.141
  AUTH_LDAP_BIND_PASSWORD: Plut0w0rk5!

media-storage:
  MEDIA_ROOT:  /media/
  MEDIA_URL:  http://10.0.146.60/
  DEFAULT_FILE_STORAGE: storages.backends.sftpstorage.SFTPStorage
  SFTP_STORAGE_HOST: 10.0.146.60
  SFTP_STORAGE_PARAMS:
    username: inwkadmin
    password: W3tw0rk5!
    allow_agent: false
    look_for_keys: false
  SFTP_STORAGE_ROOT: /home/inwkadmin
  SFTP_STORAGE_INTERACTIVE: false

email:
  SERVER_EMAIL: tito@dal.ca
  EMAIL_HOST: localhost