# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-25 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('virtualLab', '0001_initial'),
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Course Code')),
                ('title', models.CharField(max_length=50)),
                ('synopsis', models.TextField(verbose_name='Synopsis')),
                ('labs', models.ManyToManyField(blank=True, to='lab.Lab')),
                ('vlabs', models.ManyToManyField(blank=True, related_name='course_vlabs', to='virtualLab.VirtualLab', verbose_name='VIRL labs')),
            ],
            options={
                'permissions': (('take_course', 'Group/User can take this course'),),
            },
        ),
    ]
