# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-25 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('virlHost', '0001_initial'),
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='virl_host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server', to='virlHost.VirlHost'),
        ),
    ]
