# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-07 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virlHost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virlhost',
            name='last_action_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
