# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-07 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virlHost', '0003_virlhost_last_op_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virlhost',
            name='last_op_time',
        ),
    ]
