# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-25 02:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirlHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP-Address of VIRL Host')),
                ('busy', models.BooleanField(default=False)),
                ('usage', models.IntegerField(default=0)),
                ('online', models.BooleanField(default=False)),
                ('simulation', models.ManyToManyField(blank=True, to='simulation.Simulation')),
                ('users', models.ManyToManyField(blank=True, related_name='virl_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
