# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-07 01:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virlHost', '0002_virlhost_last_action_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='virlhost',
            name='last_op_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 7, 1, 42, 51, 165200)),
            preserve_default=False,
        ),
    ]
