# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-07 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virlHost', '0004_remove_virlhost_last_op_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='virlhost',
            name='bad_flag',
            field=models.IntegerField(default=0),
        ),
    ]
