# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-04 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virlHost', '0005_virlhost_bad_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virlhost',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True, verbose_name='IP-Address of VIRL Host'),
        ),
    ]
